### ISSUE TITLE
Rename confusing address props

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/app.co-api#24]
Within an app's response object, the BTC and STX address properties have the following names:

```json
{
  "BTCAddress": "...",
  "stacksAddress": "..."
}
```

For consistency's sake, would be nice to use the following:

```json
{
  "btcAddress": "...",
  "stxAddress": "..."
}
```

I gather this isn't a huge issue/priority, but does make this a little bit difficult consuming the api on the frontend — so noting here for future.

On a side note, I'd promote acronyms being treated as any other word, using prop names like `btcAddress` or `someBtcAttribute` as to avoid non-conformant camel case naming conventions (i.e. names beginning with a capital).

**Comment by markmhx** [comment]
@hstove Thoughts on the above proposal?

**Comment by hstove** [comment]
Yep, agreed on the proposed change, and would be a good easy fix after the current maker portal work :+1:
